page_elements = {'main_page_verifier_alternative_1': '//*[@id="app"]/div/div[3]/div[1]/div[1]/div[2]/div/div[2]/div[1]/div/div/div[2]/div[1]/div[1]/div/ul/li[1]/div[3]/h3/div[2]',
                 'main_page_verifier_alternative_2': '//*[@id="app"]/div/div[3]/div[1]/div[1]/div[2]/div/div[2]/div[1]/div/div/div[2]/div[1]/div[1]/div/ul/li[1]/div[2]/span/a/i',
                 'main_page_verifier_alternative_3': '//*[@id="app"]/div/div[3]/div[1]/div[1]/div/div/div[1]/div[2]/button/span',
                 'table_view_verifier': '',
                 'grid_view_verifier': '//*[@id="app"]/div/div[3]/div[1]/div[1]/div[2]/div/div[2]/div[2]/div/div/div[2]/div[2]/div/div/div[1]/div/div[1]/div[3]',
                 'device_resultset': '//*[@id="app"]/div/div[3]/div[1]/div[1]/div/div/div[2]/div[2]/div/div/div[2]/div[2]/div[1]/div/div[1]/div/table/tbody/tr[1]/td/div',
                 'stop_scan_button_verifier': '//*[@id="app"]/div/div[3]/div[1]/div[1]/div[2]/div/div[1]/div[2]/button/span/text()',
                 'stop_scan_button_verifier_new': '//*[@id="app"]/div/div[3]/div[1]/div[2]/div/div/div[1]/div[2]/button/span',
                 'start_scan_button_verifier': '//*[@id="app"]/div/div[3]/div[1]/div[1]/div[2]/div/div[1]/div[2]/button/span/text()',
                 'start_scan_button_verifier_new':'//*[@id="app"]/div/div[3]/div[1]/div[2]/div/div/div[1]/div[2]/button/span',
                 'start_stop_scan_button': '//*[@id="app"]/div/div[3]/div[1]/div[2]/div/div/div[1]/div[2]/button',
                 'start_stop_scan_button_old': '//*[@id="app"]/div/div[3]/div[1]/div[1]/div/div/div[1]/div[2]/button',
                 'clear_search_button': '//*[@id="app"]/div/div[3]/div[1]/div[2]/div/div/div[2]/div[2]/div/div/div[1]/div[2]/div[2]/a',
                 'network_list_view': '//*[@id="app"]/div/div[3]/div[1]/div[2]/div/div/div[2]/div[1]/div/div/div[2]/div[1]/div[1]/div/ul/li[1]/div[3]/h3/div[2]',
                 'session_name':'//*[@id="app"]/div/div[3]/div[1]/div[2]/div/div/div[1]/div[1]/div/span',
                 'table': '//*[@id="app"]/div/div[3]/div[1]/div[1]/div[2]/div/div[2]/div[2]/div/div/div[2]/div[1]/span[4]/span[2]',
                 'grid': '//*[@id="app"]/div/div[3]/div[1]/div[1]/div[2]/div/div[2]/div[2]/div/div/div[2]/div[1]/span[4]/span[1]',
                 'edit_session_pencil': '//*[@id="app"]/div/div[3]/div[1]/div[1]/div[2]/div/div[1]/div[1]/a',
                 'device_list_top': '//*[@id="app"]/div/div[3]/div[1]/div[1]/div[2]/div/div[2]/div[2]/div/div/div[2]/div[2]/div[1]/div/div[1]/div/table/tbody/tr/td[3]/div',
                 'empty_device_list': '//*[@id="app"]/div/div[3]/div[1]/div[1]/div[2]/div/div[2]/div[2]/div/div/div[2]/div[2]/div[1]/div/div[1]/div/table/tbody/tr[1]/td/div'}
